### ISSUE TITLE
Issue with ActiveModel::MissingAttributeError for `allow_nils: true`

### ISSUE THREAD

**Issue by konalegi** [FooBarWidget/default_value_for#74]
I have an error with `rails 4.2.10` and `default_value_for (3.0.4)`, db: postgres:9.6.
Steps to reproduce: 

``` ruby
create_table :users do |t|
  t.string :name
  t.string :surname
  t.integer :age

  t.timestamps null: false
end
```
Setup default values
```ruby
class User < ActiveRecord::Base
  default_values(
    name:      { value: 'some name',     allows_nil: false },
    surname:   { value: 'some surname', allows_nil: false },
    age:       { value: 10, allows_nil: false }
  )
end
```

```ruby
# execute query
irb(main):005:0> User.all.select(:name).first

ActiveModel::MissingAttributeError: missing attribute: surname
	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/attribute_methods/read.rb:93:in `block in _read_attribute'
	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/attribute_set.rb:31:in `block in fetch_value'
	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/attribute.rb:150:in `value'
	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/attribute_set.rb:31:in `fetch_value'
	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/attribute_methods/read.rb:93:in `_read_attribute'
	from /usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/attribute_methods.rb:50:in `__temp__375727e616d656'
	from /usr/local/bundle/gems/default_value_for-3.0.4/lib/default_value_for.rb:163:in `block in set_default_values'
	from /usr/local/bundle/gems/default_value_for-3.0.4/lib/default_value_for.rb:154:in `each'
	from /usr/local/bundle/gems/default_value_for-3.0.4/lib/default_value_for.rb:154:in `set_default_values'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `block in call'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `each'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:506:in `call'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/callbacks.rb:778:in `_run_initialize_callbacks'
```

I have monkey patch, which fixes that issue (I can make a PR, if this is valid solution): 
```ruby 
module DefaultValueFor
  module InstanceMethods
    def set_default_values
      self.class._all_default_attribute_values.each do |attribute, container|
        next unless new_record? || self.class._all_default_attribute_values_not_allowing_nil.include?(attribute)

        connection_default_value_defined = new_record? && respond_to?("#{attribute}_changed?") && !__send__("#{attribute}_changed?")

        column = self.class.columns.detect {|c| c.name == attribute}
        #
        # Monkey patch goes here
        # let's check if attribute is fetched from db.
        #
        if has_attribute?(attribute)
          attribute_blank = if column && column.type == :boolean
            attributes[attribute].nil?
          else
            attributes[attribute].blank?
          end
        else
          attribute_blank = true
        end

        next unless connection_default_value_defined || attribute_blank

        # allow explicitly setting nil through allow nil option
        next if @initialization_attributes.is_a?(Hash) &&
                (
                  @initialization_attributes.has_key?(attribute) ||
                  (
                    @initialization_attributes.has_key?("#{attribute}_attributes") &&
                    nested_attributes_options.stringify_keys[attribute]
                  )
                ) &&
                !self.class._all_default_attribute_values_not_allowing_nil.include?(attribute)

        __send__("#{attribute}=", container.evaluate(self))
        if respond_to?(:clear_attribute_changes, true)
          clear_attribute_changes [attribute] if has_attribute?(attribute)
        else
          changed_attributes.delete(attribute)
        end
      end
    end
  end
end
```

**Comment by chrisarcand** [comment]
Hi @konalegi, can you try using 3.0.5 (I've just released it)? There was a regression in 3.0.4 and the issue you're having might be fixed already.

**Comment by jkonalegi-CF** [comment]
@chrisarcand thanks, that works!

**Comment by konalegi** [comment]
@chrisarcand thanks, that works!
